AllCops:
  Exclude:
    - 'test/**/*'
    - 'examples/*'
    - 'tmp/**/*'
    - Rakefile
    - gir_ffi-gtk.gemspec
  TargetRubyVersion: 2.1

# RuboCop has no setting to accept how vim aligns parameters.
Layout/AlignParameters:
  Enabled: false

# Dot at end of line makes it clearer that the line is not done
Layout/DotPosition:
  EnforcedStyle: trailing

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# Gtk+ has a lot of accessor method starting with get_ or set_
Naming/AccessorMethodName:
  Enabled: false

# FIXME: GirFFI-Gtk uses a gir_ffi-something naming scheme.
Naming/FileName:
  Enabled: false

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# TODO: Decide on the desired style (nested or compact)
Style/ClassAndModuleChildren:
  Enabled: false

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

# Accessors are only trivial if they match the ivar name.
Style/TrivialAccessors:
  ExactNameMatch: true
