Gem::Specification.new do |s|
  s.name = 'gir_ffi-gtk'
  s.version = '0.13.1'
  s.required_ruby_version = '>= 2.2.0'

  s.summary = 'GirFFI-based Ruby bindings for Gtk+ 2 and 3'
  s.description = 'Bindings for Gtk+ 2 and 3, generated by GirFFI, with overrides.'
  s.license = 'LGPL-2.1'

  s.authors = ['Matijs van Zuijlen']
  s.email = ['matijs@matijs.net']
  s.homepage = 'http://www.github.com/mvz/gir_ffi-gtk'

  s.files =
    Dir['{lib,test,tasks,examples}/**/*', '*.md', 'Rakefile', 'COPYING.LIB'] &
    `git ls-files -z`.split("\0")
  s.test_files = `git ls-files -z -- test`.split("\0")

  s.add_runtime_dependency('gir_ffi', ['~> 0.13.1'])
  s.add_development_dependency('minitest', ['~> 5.0'])
  s.add_development_dependency('rake', ['~> 12.0'])
  s.add_development_dependency('rr', ['~> 1.1'])

  s.require_paths = ['lib']
end
